config/routes.rb
Rails.application.routes.draw do
  root 'posts#home'
  resources :posts do
  	member do
  		post 'delete'
  	end
  	collection do
  		get 'home'
  		get 'my_posts'
  	end
  end
  resources :votes do
  	collection do
  		post 'vote_post'
  	end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :votes
	def self.get_all_posts(page)
		all_post=Post.paginate_by_sql("Select * from posts where lock_version<>-1 order by id desc",:page=>page,:per_page=>10)
		count=Post.find_by_sql("Select count(*) as count from posts where lock_version<>-1").last.count
		return all_post,count
	end
	def self.get_users_all_posts(page,user)
		all_post=Post.paginate_by_sql("Select * from posts where lock_version<>-1 and user_id=#{user.id} order by id desc",:page=>page,:per_page=>10)
		count=Post.find_by_sql("Select count(*) as count from posts where lock_version<>-1 and user_id=#{user.id}").last.count
		return all_post,count
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vote.rb
class Vote < ApplicationRecord
	belongs_to :user
	belongs_to :post
	default_scope { where("lock_version<>-1") }

	def self.vote_unvote_post(post_id,user)
		user_vote=Vote.where("post_id=#{post_id} and user_id=#{user.id} and lock_version<>-1").last
		if user_vote.nil?
			Vote.create(post_id:post_id, user_id:user.id, lock_version:1)
		else
			ActiveRecord::Base.lock_optimistically = false
			user_vote.update_attribute("lock_version",-1)
			ActiveRecord::Base.lock_optimistically = true
		end
		Vote.where("post_id=#{post_id} and lock_version<>-1").length
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	include DeviseWhitelist
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
		devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
		devise_parameter_sanitizer.permit :account_update, keys: added_attrs
	end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
	extend ActiveSupport::Concern
	included do 
		before_action :configure_params, if: :devise_controller?
	end
	
	def configure_params
	  	devise_parameter_sanitizer.permit(:sign_up,keys:[:name])
	  	devise_parameter_sanitizer.permit(:account_update,keys:[:name])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def home
		@owner=false
		params[:page]||=1
		@all_post,@count=Post.get_all_posts(params[:page])
		respond_to do |format|
			format.js{render partial:"post_redirection.js.erb", locals:{from: :home, page: params[:page]}}
			format.html{render template:"posts/home.html.erb", locals:{page: params[:page], from: "Home"}}
		end
	end
	def my_posts
		@owner=true
		params[:page]||=1
		@all_post,@count=Post.get_users_all_posts(params[:page],current_user)
		respond_to do |format|
			format.js{render partial:"post_redirection.js.erb", locals:{from: :my_posts, page: params[:page]}}
			format.html{render template:"posts/home.html.erb", locals:{page: params[:page], from: "Home"}}
		end
	end
	def new
		@post=Post.new
		render partial:"post_redirection.js.erb", locals:{from: :new}
	end
	def create
		@owner=true
		@post=Post.create(title: params[:post][:title], description: params[:post][:description], user:current_user)
		render partial:"post_redirection.js.erb", locals:{from: :create}
	end
	def edit
		@post=Post.find_by_id params[:id]
		render partial:"post_redirection.js.erb", locals:{from: :edit}
	end
	def update
		@owner=true
		@post=Post.find_by_id params[:id]
		@post.update_attributes(title: params[:post][:title], description: params[:post][:description])
		render partial:"post_redirection.js.erb", locals:{from: :update}
	end
	def delete
		@post=Post.find_by_id params[:id]
		ActiveRecord::Base.lock_optimistically=false
		@post.update_attribute("lock_version",-1)
		ActiveRecord::Base.lock_optimistically=true
		render partial:"post_redirection.js.erb", locals:{from: :delete}
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
	def vote_post
		@vote_count=Vote.vote_unvote_post(params[:post_id],current_user)
		render partial: 'votes/vote_redirection.js.erb', locals:{post_id:params[:post_id]}
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExpressPost</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title" id="modal_heading">Modal Heading</h4>
          <button type="button" class="close" data-dismiss="modal" id="close_modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body" id="modal_body">
          Modal body..
        </div>

      </div>
    </div>
  </div>
  


  <%=render 'shared/navbar'%>

  <main role="main">

    <div id="user_detail">
      <!-- Will be handled by AJAX -->
    </div>

    <div class="album py-5 bg-light">
      <div class="container" id="main_timeline">
        <%=yield%>
      </div>
    </div>

  </main>

</body>
</html>

app/views/posts/_edit.html.erb
<%= form_for @post,:url=>post_path, html: { multipart: true ,method: 'patch',:id=>"edit_post"}, remote: true, authenticity_token: true do |f| %>
<div class="form-group">
	<%=f.label :title%>
	<%=f.text_field :title,class:"form-control"%>
	</div>
    <div class="form-group">
   <%=f.label :description%>
   <%= f.text_area :description,class:"form-control"%>
   </div>
      	<!-- Modal footer -->
        <div class="modal-footer" id="modal-footer">
          <%= f.submit "Update" ,id:"new_post_create", class:"btn btn-primary", onclick: "return validate_post();"%>
          <button type="button" class="btn btn-danger" data-dismiss="modal" id="modal_close_button">Cancel</button>
        </div>
<%end%>
<script type="text/javascript">
  function validate_post()
  {
    post_title=$('#post_title').val();
    post_description=$('#post_description').val();
    if(post_title=="")
    {
      alert("Kindly Provide a Title to your Post");
      return false;
    }
    if(post_description=="")
    {
      alert("Kindly Write Something as Post");
      return false;
    }
    return true
  }
</script>

app/views/posts/_new.html.erb
<%= form_for @post,:url=>posts_path, html: { multipart: true ,method: 'post',:id=>"new_post"}, remote: true, authenticity_token: true do |f| %>
<div class="form-group">
	<%=f.label :title%>
	<%=f.text_field :title,class:"form-control"%>
	</div>
    <div class="form-group">
   <%=f.label :description%>
   <%= f.text_area :description,class:"form-control"%>
   </div>
      	<!-- Modal footer -->
        <div class="modal-footer" id="modal-footer">
          <%= f.submit "Create" ,id:"new_post_create", class:"btn btn-primary", onclick: "return validate_post();"%>
          <button type="button" class="btn btn-danger" data-dismiss="modal" id="modal_close_button">Cancel</button>
        </div>
<%end%>
<script type="text/javascript">
  function validate_post()
  {
    post_title=$('#post_title').val();
    post_description=$('#post_description').val();
    if(post_title=="")
    {
      alert("Kindly Provide a Title to your Post");
      return false;
    }
    if(post_description=="")
    {
      alert("Kindly Write Something as Post");
      return false;
    }
    return true
  }
</script>

app/views/posts/_post_block.html.erb
<div class="col-md-3" id="post_block_<%=post.id%>">
    <div class="card mb-4 box-shadow" style="max-width:100%;">
      <div class="card-body">
        <center>
          <h3 ><%if @owner%>
            <%=link_to "#{post.title}",edit_post_path(post.id), id: "post_title_#{post.id}" , remote: true%>
          <%else%>
            <%=post.title%>
          <%end%></h3>
        </center>
        <label style="color:grey"><i>by:-</i><%=post.user.name%></label>
        <p class="card-text" id="post_description_<%=post.id%>"><%=post.description%></p>
        <hr>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <div id="like_div"><label id="like_count_<%=post.id%>"><%=post.votes.length%></label>&nbsp;<%=link_to "<img src='#{asset_path('like.png')}' height='20' width='20' title='Like'>".html_safe,vote_post_votes_path(post_id:post.id),method: 'post', remote: true%></div>
            <%if @owner%>
            &nbsp;
              <div id="delete_div"><%=link_to "<img src='#{asset_path('delete.png')}' height='20' width='20' title='Delete Post'>".html_safe,delete_post_path(id:post.id),method: 'post', remote: true%></div>
            <%end%>
          </div>
          <small class="text-muted"><%=time_ago_in_words(post.created_at) %></small>
        </div>
      </div>
    </div>
  </div>

app/views/posts/_post_listing.html.erb
<h1><%=page_heading%></h1>
<div class="row" id="user_iteration">
  <%@all_post.each do|post|%>
  <div class="col-md-3" id="post_block_<%=post.id%>">
    <div class="card mb-4 box-shadow" style="max-width:100%;">
      <div class="card-body">
        <center>
          <h3 >
          <%if @owner%>
            <%=link_to "#{post.title}",edit_post_path(post.id), id: "post_title_#{post.id}" ,remote: true%>
          <%else%>
            <%=post.title%>
          <%end%>
          </h3>
        </center>
        <label style="color:grey"><i>by:-</i><%=post.user.name%></label>
        
        <p class="card-text" id="post_description_<%=post.id%>"><%=post.description%></p>
        <hr>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <div id="like_div"><label id="like_count_<%=post.id%>"><%=post.votes.length%></label>&nbsp;<%=link_to "<img src='#{asset_path('like.png')}' height='20' width='20' title='Like'>".html_safe,vote_post_votes_path(post_id:post.id),method: 'post', remote: true%></div>
            <%if @owner%>
            &nbsp;
              <div id="delete_div"><%=link_to "<img src='#{asset_path('delete.png')}' height='20' width='20' title='Delete Post'>".html_safe,delete_post_path(id:post.id),method: 'post', remote: true%></div>
            <%end%>
          </div>
          <small class="text-muted"><%=time_ago_in_words(post.created_at) %></small>
        </div>
      </div>
    </div>
  </div>
  <%end%>
</div>

app/views/posts/_post_redirection.js.erb
<%case from%>
<%when :home%>
$("#home_page_content").html("<%=j render partial: 'posts/post_listing',locals:{page_heading:'All Posts'}%>");
$('#paginate_content').html("<%=j render partial: 'shared/paginate',locals:{page: page, from: 'Home'}%>");
<%when :new%>
	$('#modal_heading').html("Create Post");
	$("#modal_body").html("<%=j render 'posts/new',post:@post%>");
	$("#open_form_modal").click();
<%when :create%>
	$('#modal_heading').html("");
	$("#modal_body").html("");
	$("#close_modal").click();
	$('#user_iteration').prepend("<%=j render 'posts/post_block',post:@post%>")
<%when :edit%>
	$('#modal_heading').html("Edit Post");
	$("#modal_body").html("<%=j render 'posts/edit',post:@post%>");
	$("#open_form_modal").click();
<%when :update%>
	$('#modal_heading').html("");
	$("#modal_body").html("");
	$("#close_modal").click();
	$('#post_title_<%=@post.id%>').html("<%=@post.title%>")
	$('#post_description_<%=@post.id%>').html("<%=@post.description%>")
<%when :my_posts%>
$("#home_page_content").html("<%=j render partial: 'posts/post_listing',locals:{page_heading:'My Posts'}%>");
$('#paginate_content').html("<%=j render partial: 'shared/paginate',locals:{page: page, from: 'My_Posts'}%>");
<%when :delete%>
$("#post_block_<%=@post.id%>").hide();
<%end%>

app/views/posts/home.html.erb
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" id="open_form_modal" style="display: none;">
  Add Post
</button>
<%=link_to "Add Post",new_post_path, class: "btn btn-primary" ,style: "float:right; margin-right: 2%; margin-top: 1%;", remote: true%>

<div id="home_page_content">
<%=render partial:"posts/post_listing.html.erb", locals:{page_heading:"All Posts"}%>
</div>
<div id="paginate_content"><%=render partial:"shared/paginate.html.erb", locals:{page: page, from: "Home"}%></div>

app/views/shared/_navbar.html.erb
<header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">Express Posts offers you to express your views and thoughts in form of beautilutty crafted blogs where you get complete freedom to showcase your writing talents!</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white"><%=(current_user) ? current_user.name : "Nav-Links"%></h4>
              <ul class="list-unstyled">
                <li><%=link_to "Home",home_posts_path,method: :get,class:"text-white",remote: true%></li>
              <%if current_user%>
                <li><%=link_to "My Posts",my_posts_posts_path(user_id: current_user.id),method: :get,class:"text-white",remote: true%></li>
                <li><%=link_to "Logout",destroy_user_session_path,method: :delete,class:"text-white"%></li>
              <%else%>
                <li><%=link_to "Login",new_user_session_path,method: :get,class:"text-white"%></li>
                <li><%=link_to "Sign-up",new_user_registration_path,method: :get,class:"text-white"%></li>
              <%end%>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Express Posts</strong>
            <div id="breadcrumb_content"></div>
          </a>
          <button class="navbar-toggler" type="button" id="sandwich" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

app/views/shared/_paginate.html.erb
<div style="float:right;">
<%page=page.to_i
@count=@count.to_i%>
	<%if page>1%>
		<%if from=="Home"%>
			<%=link_to "<<Previous<<", home_posts_path(page: page-1),method: :get,remote: true%>
		<%else%>
			<%=link_to "<<Previous<<", my_posts_posts_path(user_id: current_user.id, page: page-1),method: :get,remote: true%>
		<%end%>
	<%end%>
	<b>|Page: <%=page%>|</b>
	<%if (page*10)<@count%>
		<%if from=="Home"%>
			<%=link_to ">>Next>>",home_posts_path(page: page+1),method: :get,remote: true%>
		<%else%>
			<%=link_to ">>Next>>",my_posts_posts_path(user_id: current_user.id,page: page+1),method: :get,remote: true%>
		<%end%>
	<%end%>
</div>

app/views/votes/_vote_redirection.js.erb
$("#like_count_<%=post_id%>").html("<%=@vote_count%>");